### ISSUE TITLE
Tagify in a modal - selection causes the modal to scroll-to-top

### ISSUE THREAD

**Issue by gidzr** [yairEO/tagify#1170]
## Prerequisites

- [x] I am running the latest version (using the latest JQUERY version:  src="https://cdnjs.cloudflare.com/ajax/libs/tagify/4.17.6/jQuery.tagify.min.js and also tested with javascript version at https://cdn.jsdelivr.net/npm/@yaireo/tagify)
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Demo
- sorry, am not able to do this - apologies, but if I resolve the problem, I'll post my answer.
- for now, just hoping I'm not the only one to come across this issue

### Explanation

- **What is the expected behavior?**
- I've created a modal with tagify input
- The modal is longer than the page, so I need to scroll down the modal to reach the tagify input field
- When I select an option, I expect the scroll / page position to remain unaffected

- **What is happening instead?**
- When I select an option from the tagify whitelist, the modal auto-scrolls to top

- **What error message are you getting?**
- No error message, just strange behaviour in modal

I've tested the same code in a normal html page, and this auto-scroll-to-top is not occurring.. when I cut and paste the same code into a modal, it has this weird scroll-to-top behaviour. 

I've also tested all the events shown in the tagify readme, and this behaviour only occurs when the 'add' event occurs.

I have other input fields in the modal, including a select2 tags/multiple  - and these fields do not exhibit the same weirdness.

**Comment by gidzr** [comment]
I've discovered it's a Bootstrap 5.1+ conflict. 

I'm not sure whether it's Tagify or Bootstrap that has a 'bug', so this is my submission to the Bootstrap team: https://github.com/twbs/bootstrap/issues/37881

It includes a codepen which demonstrates the issue:
https://codepen.io/gidzr/pen/OJwjMNN

Cheers! :)

**Comment by yairEO** [comment]
What made you think this is a Bootstrap issue?

**Comment by gidzr** [comment]
You're right - I can't be sure whether Tagify hasn't been updated for new Bootstrap 5.1+, or whether it's a Bootstrap bug introduced 5.1+..

Just easier for me to infer (probability-wise) it's a Bootstrap bug because:
1. It's a new (undesirable) behaviour that's been introduced rather than the cessation of Tagify functionality
2. It's only happened after a major Bootstrap change in a new Bootstrap series.. going 5.0 to 5.1 in the new 5 series... and not a change with Tagify versioning
3. The new thing is related to modal only, not on regular pages (inconsistent).. 
4.  It only happens on the  .on('add') click listener for words in a whitelist, but not from .on(add) keyboard listener for dynamically added words (inconsistent)

So ... if it's the fault of Tagify, I can't understand what "improvement" to Bootstrap would cause an inconsistency between click vs keyboard listener behaviour on the same listening event, but only for modals, and not in normal pages.

Do you think the issue is Tagify or Bootstrap?

**Comment by yairEO** [comment]
I've analyzed the bug and it's Bootstrap's fault. 

Tagify's dropdown list is injected to the `<body>` element and I think Bootstrap is treating it in a weird way, since a click-outside should close the modal, but it doesn't get closed in this situation (which is easily done since you can know if a mouse click was made on top of a modal, even if the element is not within it in the DOM) and then scrolls to the top.

They didn't account for such cases maybe.

You can bypass this by setting the Tagify's `dropdown` setting with an additional sub-setting:

```
appendTarget: document.querySelector('.modal-content'),
```

This works if you have just one modal... if you have more you will need to place a DOM node reference to the correct one.

**Comment by gidzr** [comment]
Awesomeness!.. Thanks heaps Yair!

As mentioned above I posted bug to Bootstrap - but they didn't really look into it. I've updated my bug report to Bootstrap with your comments above. Hopefully that will get their attention, and they can possibly fix it at their end. ;P (well.. highly unlikely but worth a shot).

https://github.com/twbs/bootstrap/issues/37881

Cheers

**Comment by gidzr** [comment]
Hey Yair - thanks for your time on this.. Funny it was actually a Bootstrap 'improvement' that did turn out to be the issue. Maybe Bootstrap 5.4 will have your suggestions implemented :`D

**Comment by gidzr** [comment]
HOLY COW!..pheww.. I've just spent a full day trouble shooting this.. 

I implemented your fix "appendTarget: document.querySelector('.modal-content')," .. thinking job done. But the tagify options stopped loading. It worked in CodePen, but not my site.. so I knew it was some type of conflict.

I meticulously removed blocks and lines of code.. re-created separate sandboxes.. and still no luck..

Then finally I discovered something un-b-fkn-lievable.. 

The "appendTarget: document.querySelector('.modal-content'),"  is AFFECTED BY BOOTSTRAP CLASSES!!!  (ie. d-flex, row, container, wrapper, etc)

I've update the CodePen to illustrate: https://codepen.io/gidzr/pen/OJwjMNN

Instead of the selections appearing at the site of the tagify intput box, it appears completely offset (sometimes out of viewport).

I'm adding a separate BUG for this. :)

**Comment by yairEO** [comment]
I think this is a Tagify bug that miscalculates the suggestions' menu position when `appendTarget` is used. I will investigate. 

I don't see a relation between the miscalculation and any CSS coming from Bootstrap. 
The positioning algorithm should place the menu relative to the Tagify component.

**Comment by gidzr** [comment]
In the codepen the weird offset didn't occur until I nested the tagify-input field in Divs.. When I removed the bootstrap classes the suggestion box was still offset but in a different location.
Therefore from playing around with Codepen I can see both the Div nesting and CSS have an impact on the new positioning, albeit the css is a lesser extent.

I've got a workaround, although it reset all the prettifying css I'd added..  Not urgent, but would be great when it's fixed. :)

**Comment by gidzr** [comment]
FYI, just came across a similar problem with Select2.. their solution is same as yours - appending to the modal.. ;)
https://select2.org/troubleshooting/common-problems (Select2 does not function properly when I use it inside a Bootstrap modal.)

**Comment by Diana-Alex-Rodrigues** [comment]
Hello @gidzr ,
Did you manage to get this to work ?
I already tried every tip and still does not work.

**Comment by yairEO** [comment]
@Diana-Alex-Rodrigues - you should bug `Bootstrap` github to solve this, they are in fault here

**Comment by gidzr** [comment]
Hi @Diana-Alex-Rodrigues .. 

To confirm, did you try:
```var appendTarget = $(targetElem).parents('.modal').find('.modal-content')[0]```

Then when initiating tagify:

```
      new Tagify(inputSelector,{              
         whitelist: optionTags,
         dropdown: {
            position      : 'text',
            appendTarget : appendTarget,

```
