### ISSUE TITLE
Plugin conflicts with Vue.js

### ISSUE THREAD

**Issue by pratamatama** [yairEO/tagify#219]
I'm trying to use this plugin with Laravel in which I have some of my web components built in Vue.js.
It seems like the plugin created a new tag. In this case: `<tags>`.

On the console, you can see that Vue is looking for that component which is not exist.

![Screenshot (65)](https://user-images.githubusercontent.com/42239243/56078171-1d439700-5e0f-11e9-9202-a3b7f2563508.png)

Please take a look at my script, I did follow the instruction from the docs, am I doing something wrong?
````
import Tagify from '@yaireo/tagify'

var controller
var input = document.getElementById('tag-input')

var tagify = new Tagify(input, {
    whitelist: [],
    maxTags: 5
})

tagify.on('input', function (e) {
    var value = e.detail
    tagify.settings.whitelist.length = 0

    controller && controller.abort()
    controller = new AbortController()

    axios.get('tags').then(response => {
        tagify.settings.whitelist = response.data
        tagify.dropdown.show.call(tagify, value)
    })
})
````

This one is my `.blade.php` file:
````
<div class="form-group">
  <label for="tags">{{ __('posts.tags.label') }}</label>
  <input name="tags" value="{{ old('tags') }}" type="text" class="form-control form-control-dark {{ $errors->has('tags') ? 'is-invalid' : '' }}" id="tag-input" placeholder="{{ __('posts.tags.placeholder') }}">
  <span class="invalid-feedback">{{ $errors->first('tags') }}</span>
</div>
````

Thanks in advance.

**Comment by yairEO** [comment]
Yes it does creates that custom `<tags>` element, but does it work for you?

Is that problem only with this annoying message in the console or is there an actual problem?

**Comment by pratamatama** [comment]
Unfortunately, it does not work. It was blocked by Vue because "Vue" think it was his component. The input does not seems to be appeared at all.

**Comment by yairEO** [comment]
Ok Sir, I just released a new version `2.17.0` which might solve your situation.

See [this section](https://github.com/yairEO/tagify#dom-templates)

You can change the tag name to be anything else you would like and see if that works for you.

**Comment by pratamatama** [comment]
Nothing worked, it still recognized as Vue component because it's custom tag. The problem is in the custom tag I guess.

**Comment by yairEO** [comment]
How is that possible, I've advised you in the previous comment to change the tag name but then you answered me *"Nothing worked, it still recognized as Vue component because it's custom tag."* 

Did you a change it? what did you change it to?

**Comment by pratamatama** [comment]
I changed to anything but still won't work. But I just found a solution for this issue, just ignore the element from the Vue instance itself. Not a really good solution but it fixed the warning.
````
Vue.config.ignoredElements = ['tags']
````

**Comment by yairEO** [comment]
But why do you still have custom tag names if you claim you've changed it?
