### ISSUE TITLE
Dropdown should scroll with input

### ISSUE THREAD

**Issue by cowwoc** [yairEO/tagify#314]
I am expecting the input and downdrop menu to scroll as a single unit. The attached video shows one scrolling off the screen, leaving the other behind.
![video](https://user-images.githubusercontent.com/633348/65564318-7feea200-df1a-11e9-9715-7bfd1ec06b0d.gif)

**Comment by yairEO** [comment]
This is because the inputs are "position:sticky".
I did not make the dropdown follow them on purpose because that would require extra code which is almost 99% won't be in use since who puts an input to be sticky? I've never seen a design like that on a real website or system, it's highly unusual.

I've implemented it on my demo page because the design demands this UX, as the input should follow the user because each left-side section can get quite long.

**Comment by fryiee** [comment]
@yairEO I'm having a similar issue with this, and it is not the input itself that is sticky, but the parent. This behaviour still exists (scrolling will cause the dropdown to scroll away). The use case here, which is fairly common, is a fixed search sidebar with tag inputs. What's the best workaround for this?

**Comment by yairEO** [comment]
this is not a problem at all, I've simply left it as is in the demo page because this should be dealt with by the developer whos implementing Tagify.

Tagify has no way of knowing which element is sticky and which parent has scrollbars.
Technically I can add code that iterates over all parent nodes and checks which has scrollbar, but it might be buggy and inflate the codebase for such rare use-case (IMHO).

what you should do is what I've advised [here](https://github.com/yairEO/tagify/issues/400)

Add a scroll event listener to the element which has scrollbars and re-position the dropdown:

    tagify.dropdown.position.call(tagify)
