### ISSUE TITLE
Max Suggestion to be displayed from whitelist && some unexpected behaviours!

### ISSUE THREAD

**Issue by YuriScarbaci** [yairEO/tagify#43]
Can you please implement a new setting parameter that allows us to set how many suggestion the whitelist should display? 
if not that, a callback on the event "on change" would be good too to actually manually handle the whitelist  and displaying a maximum number of results. basically something like this : 
```
function(request, response) {
        var results = element.filter(myarray, request.term,maxSuggestions);
        response(results.slice(0, maxSuggestions));
    }
```
Also please release a pre-compiled version of this to be implemented on vanilla html without needing pre-processors.

Also to correctly display the input like it's supposed to be displayed in the demo i had to manually hide the element i "tagified", i think it should be integrated in the tagify() function itself to actually hide the element that will only hold the value.

Great job btw!

**Comment by YuriScarbaci** [comment]
I Implemented the function for maxium suggestion my self, I did the following changes:

Added the following code inside the default values of the setting initialization
`maxSuggestions: Infinity`

I changed 
`for (i = this.settings.whitelist.length; i--; )
                    OPTIONS += "<option>" + this.settings.whitelist[i] + "</option>";`

into
` if (this.settings.maxSuggestions === Infinity) {
                for (i = this.settings.whitelist.length; i--; )
                    OPTIONS += "<option>" + this.settings.whitelist[i] + "</option>";
            } else {
                for (i = this.settings.maxSuggestions; i--; )
                    OPTIONS += "<option>" + this.settings.whitelist[i] + "</option>";
            }`

Tried this myself and it's workin as i wanted it to.

**Comment by yairEO** [comment]
what do you mean a `pre-compiled` version? do you mean `post-compiled` maybe?

There are 2 folders: `dist` and `src`, everything is there, it's pretty common practice

**Comment by YuriScarbaci** [comment]
no i didn't realize about that src folder so i got my hands on the css from the demo-page, and it looks like something went missing from there, it's currently working as i want in the project, just double check it works in yours too, i'm referencing the input by a getelementbyid, not with the selector you are using in the example, dunno if that have anything to do with it, just check it out.

About the maxSuggestion function, did you revise it? it's working correctly in my project, but i dunno if it's as optimized as it should, i'm mainly a php back-end developer so i would like someone more expert to optimize it.

Thanks a lot for your time and work so far btw, great plugin.

**Comment by yairEO** [comment]
I did take a look at it. You forgot to put this line `filtredArray = this.filterTagsSuggestions(inputStr);` inside the `var` statement a line after it. should be inside.

Anyway, I am in the process of integrating a 3rd party autosuggestion library into this script and only leave *datalist* support as a fallback, so I don't want to inflate the source code with the `filterTagsSuggestions` function you have written above. I aim to simply things and go for an external solution which is more flexible in terms of styling and content control.

**Comment by yairEO** [comment]
I have a better idea, wait

**Comment by yairEO** [comment]
I think this method will do the trick, but it would have to be called each on an `input` event callback:

    buildDataList : function(){
        var OPTIONS = "",
            inputValue = this.DOM.input,
            i,
            datalist = document.createElement('datalist'),
            suggestionsCount = this.settings.maxSuggestions || Infinity;

        datalist.id = 'tagifySuggestions' + this.id;
        datalist.innerHTML = "<label> \
                                select from the list: \
                                <select> \
                                    <option value=''></option> \
                                    [OPTIONS] \
                                </select> \
                            </label>";

        for( i=this.settings.whitelist.length; i--; ){
            var value = this.settings.whitelist[i];
            if( suggestionsCount-- && value.indexOf(inputValue) == 0 ) // make sure the input value matches the begning part of this suggestion item
                OPTIONS += "<option>"+ value +"</option>";
        }

        datalist.innerHTML = datalist.innerHTML.replace('[OPTIONS]', OPTIONS); // inject the options string in the right place

      //  this.DOM.input.insertAdjacentHTML('afterend', datalist); // append the datalist HTML string in the Tags

        return datalist;
    }

**Comment by YuriScarbaci** [comment]
because I have a request from a client to generate the suggestions from all the fields already present in the database, without repeated field, but the field he wants to be "autocompleted from already inputed fields" isn't a select, it's a free-text input string, meaning that even a single character difference makes up for a whole new different suggestion, and since the database is HEAVY (i know, it's dumb, but that's what they want, i told them about performance issues and other possible solutions, but they refused to listen, and wanted it no matter what) the suggestion list will have like more than 3k suggestions.

**Comment by YuriScarbaci** [comment]
> I think this method will do the trick, but it would have to be called each on an input event callback:

i don't see much difference with what i did in the buildFiltredDatalist, it's basically building the datalist eachtime the input change, no?

your version iterate the whole whitelist even when you have maxsuggestion set to 5, my version stop iterating as soon as the suggestion count is reached, no?

**Comment by yairEO** [comment]
updated the code to break once the maximum number of suggestions has been met.

There is a huge difference between my solution and yours, which is mine is much less code (which is very important) and also it is easier to understand since it is very intuitive

**Comment by YuriScarbaci** [comment]
will try it out tomorrow and let you know if it works out as it should, thanks a lot for your time and help!

just one last doubt, can't i bind it automatically from the already implemented onInput event handler of your plugin instead of this:

> ```
> // dynamically build the suggestions list when the input changes
> tagify.DOM.input.addEventListener('input', function(){
>     tagify.DOM.datalist = tagify.buildDataList();
> }
> ```

setting it up like this:
```

on the onInput event I added the following function call:
`this.DOM.datalist = this.buildFiltredDataList(value);`
right before:
`this.DOM.input.parentNode.appendChild(this.DOM.datalist);`
```
switching out `this.buildFilredDataList(value) ` with `this.buildDataList()` ?

**Comment by yairEO** [comment]
You would have to change the original source code and that is bad practice, since you won't be able to easily sync with this repo once I update it because your code will be different than the repo's.

what you suggest is possible but not a good idea..

**Comment by YuriScarbaci** [comment]
so are you going to change the buildDataList on the official repo too?

**Comment by yairEO** [comment]
Yes, I will change it completely, to use an outside script which will manage the suggestions list, and then the tagify code will be isolated from the suggestions list, which is something extra, as I see it. 
I want this script to focus on the tags and not on the suggestions.

**Comment by YuriScarbaci** [comment]
okay, thanks a lot for everything then, looking forward to the new version, by what i understand it will be even more compatible with older browser that don't even have the native datalist!
